import type { Metadata } from 'next';
import { Noto_Sans, Allison } from 'next/font/google';
import '../globals.css';
import 'ldrs/react/Grid.css';

const noto_Sans = Noto_Sans({
  subsets: ['latin'],
  variable: '--font-noto_sans',
});

const allison = Allison({
  subsets: ['latin'],
  variable: '--font-allison',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Genuss Hotel',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${noto_Sans.variable} ${allison.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
