// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "common": {
    "buttons": {
      "bookNow": "Book Now",
      "bookRooms": "Book Rooms",
      "contactUs": "Contact Us",
      "learnMore": "Learn more for details",
      "completeBookNow": "Complete Book Now",
      "send": "Send",
      "previous": "Previous",
      "next": "Next"
    },
    "labels": {
      "loading": "Loading...",
      "submitting": "Submitting...",
      "error": "Error",
      "success": "Success",
      "selectDate": "Select date",
      "total": "Total",
      "bookingSummary": "Booking Summary",
      "noResult": "No results"
    },
    "forms": {
      "bookingForm": {
        "title": "Book Rooms",
        "checkIn": "Check In",
        "checkOut": "Check Out",
        "adult": "Adult",
        "child": "Child",
        "toast": {
          "success": "Room added to booking!",
          "error": "Failed to add room to booking, please try again later.",
          "validation": {
            "checkIn": "Please select check-in date.",
            "checkOut": "Please select check-out date.",
            "invalidDateRange": "Check-out date must be after check-in date."
          }
        }
      },
      "contact": {
        "title": "Leave us your info",
        "titleBooking": "Complete your booking",
        "descriptions": "and we will get back to you",
        "descriptionsBooking": "Fill in your details to complete the booking",
        "form": {
          "fullName": "Full Name",
          "email": "Email",
          "country": "Country",
          "phone": "Phone",
          "message": "Message (optional)",
          "mr": "Mr",
          "mrs": "Mrs",
          "send": "Send Message",
          "toast": {
            "success": {
              "booking": "Booking submitted successfully! We will contact you soon.",
              "contact": "Message sent successfully! We will get back to you."
            },
            "error": "Failed to submit. Please try again.",
            "validation": {
              "roomLength": "Please book at least one room to your booking"
            }
          }
        }
      }
    }
  },

  "menu": {
    "home": "home",
    "services": "services",
    "rooms": "rooms",
    "roomDetails": "room details",
    "bookingDetails": "booking details",
    "booking": "booking",
    "contact": "contact"
  },

  "home": {
    "title": "Welcome to Genuss Hotel",
    "description": "Modern Mountain Retreat in the Heart of Tam Dao",
    "introduce": {
      "title": "WHY CHOOSE GENUSS TAM DAO ?",
      "features": {
        "location": {
          "title": "PRIME CENTRAL LOCATION",
          "description": "Just a few steps from the Central Square and the iconic Stone Church"
        },
        "spaces": {
          "title": "MODERN & RELAXING SPACES",
          "description": "Minimalist design with large windows opening toward cloud-filled mountain views"
        },
        "pool": {
          "title": "ALL-YEAR OUTDOOR SWIMMING POOL",
          "description": "Enjoy Tam Dao in the most refreshing and relaxing way"
        },
        "facilities": {
          "title": "FULL FACILITIES & 24/7 SERVICE",
          "description": "Gym, sauna, restaurant, bar, and dedicated round-the-clock support"
        }
      }
    },
    "summary": {
      "title": "A modern hideaway amidst the hustle and bustle of Tam Dao",
      "descriptions": "GENUSS offers the perfect balance: close enough for you to walk and explore the town, but quiet enough for you to find a pleasant silence<lineBreak></lineBreak><lineBreak></lineBreak> 94 spacious rooms, overlooking the Tam Dao cloud city, combined with an outdoor swimming pool, gym, sauna and 24/7 service - all create a gentle, effortless and inspiring vacation.",
      "rate": "on {social}",
      "rooms": "{countRooms} rooms"
    },
    "testimonial": {
      "title": "Testimonial"
    }
  },

  "rooms": {
    "title": "Our Rooms",
    "descriptions": "A total of 94 rooms with 7 room categories to suit all customers' needs. The interior is carefully selected, fully equipped, ensuring maximum comfort and privacy.",
    "viewDetails": "View Details",
    "viewAllRooms": "View All Rooms",
    "recommended": "more rooms",
    "priceJSX": "From <price>{value}</price> / Night",
    "price": "From {value} / Night",
    "maxOccupancy": "Maximum  {maxOccupancy} people",
    "room": {
      "title": "{name} Room",
      "roomFeatures": "Room features",
      "bed": "Bed",
      "space": "Space",
      "maximum": "Maximum",
      "view": "View",
      "amenities": "Amenities",
      "roomGallery": "Room Gallery",
      "people": "people",
      "name": {
        "executive-suite-city-view": "Executive Suite City View",
        "royal-suite": "Royal Suite",
        "royal-honeymoon": "Royal Honeymoon",
        "junior-deluxe-mountain-view": "Junior Deluxe Mountain View",
        "premium-deluxe-city-view": "Premium Deluxe City View",
        "deluxe-twin-mountain-view": "Deluxe Twin Mountain View",
        "superior-double-city-view": "Superior Double City View"
      },
      "description": {
        "superior-double-city-view": "Superior Double Room (City View) - approximately 25 m², furnished with one large double bed and a window overlooking Tam Đao town's skyline. The room features a modern, minimalist design with a comfortable seating area, flat-screen TV, air conditioning and complimentary Wi-Fi. The en-suite bathroom includes a walk-in shower, bath linens and essential toiletries.\nSituated close to the town centre and offering a city view, this room is an ideal choice for couples or two guests seeking a relaxing stay with easy access to Tam Dao's vibrant atmosphere.",
        "executive-suite-city-view": "The Executive Suite City View Room spans approximately 38 m², featuring one expansive King-size bed and commanding views of Tam Dao town centre. The suite is stylishly appointed with a neutral palette, light wood accents, floor-to-ceiling windows inviting natural daylight and showcasing misty mountain or town vistas. Amenities include a comfortable lounge seating area, dedicated workspace, a fully stocked minibar, modern air-conditioning and complimentary Wi-Fi. The en-suite bathroom boasts both a bathtub and a walk-in shower, crisp white linens and premium toiletries.\nThis suite is ideal for guests seeking an elevated getaway — where leisure meets refined style, in the heart of Tam Dao.",
        "royal-suite": "The Royal Suite spans approximately 52 m², featuring one large King-size bed and wide windows overlooking the bustling boulevard or central square of Tam Dao—offering a view into the town's heartbeat and nighttime lights. The suite boasts a generously spacious layout with a separate living area—relaxing sofa, work desk and fully stocked minibar. The neutral-toned decor and generous natural light from large windows enhance the feeling of open, calm luxury. The en-suite bathroom includes both a bathtub and a walk-in shower, crisp white linens and premium toiletries.\nThis suite is an ideal choice for guests seeking an upgraded stay: more than just a restful night, it's about enjoying refined, modern resort-style living in the heart of Tam Dao.",
        "royal-honeymoon": "The Royal Honeymoon Room spans approximately 48 m², features one large King-size bed and offers a view of the misty mountains of Tam Dao. The suite is elegantly styled with modern furnishings, abundant natural light, light wood accents and soft touches, creating a space that is both cozy and contemporary. Amenities include a separate lounge area, a small work desk, a fully stocked minibar, complimentary Wi-Fi and modern air-conditioning. The luxury en-suite bathroom includes both a bathtub and a walk-in shower, crisp white linens and premium toiletries.\nThis suite is the perfect choice for couples seeking a special getaway — where romance meets refined comfort, nestled in the tranquil mountain air of Tam Dao.",
        "junior-deluxe-mountain-view": "The Deluxe Double Room (Mountain View) offers approximately 28 m² of space with one large double bed and a window framing the serene mountain landscape of Tam Dao — where morning mist lingers gently. The room features a premium, minimalist design with light wood tones and abundant natural light. Amenities include a seating area, compact work desk, flat-screen TV, modern air-conditioning, a mini-bar and complimentary Wi-Fi. The en-suite bathroom comes with a walk-in shower or bathtub (depending on room), pristine white towels and premium toiletries.\nThis room is perfect for couples or guests seeking a tranquil mountain view stay, blending nature's calm with modern, comfortable resort-style living.",
        "premium-deluxe-city-view": "The Premium Deluxe City View Room offers approximately 35 m² of elegantly designed space, featuring a large King-size bed and a window overlooking the vibrant centre of Tam Dao town—allowing you to feel connected yet comfortably secluded. The room presents a modern aesthetic with neutral tones, light wood accents and abundant natural daylight, accompanied by a relaxing lounge chair, compact work desk and well-stocked minibar. The en-suite bathroom is upscale, offering both a bathtub and walk-in shower, pristine white linens and premium toiletries.\nThis room is perfect for those seeking an upgraded stay: it's not just about rest—it's about enjoying refined comfort and wellness in the heart of Tam Dao.",
        "deluxe-twin-mountain-view": "The Superior Triple Room, around 28 m²,with 32 rooms, features one double bed and one single bed, offering scenic views of the mountain of Tam Dao. The room boasts a modern design with light tones and timber accents, and a large window to welcome natural daylight. Amenities include a seating area, small work desk, flat-screen TV, air conditioning, complimentary Wi-Fi and a compact minibar. The en-suite bathroom is equipped with a walk-in shower and/or bathtub (depending on room), fresh towels and complimentary toiletries.\nThis room is ideal for a small family or a trio of friends seeking a spacious, modern retreat while staying just steps from the heart of Tam Dao—perfect for both relaxation and exploration."
      }
    }
  },

  "facilities": {
    "title": "Hotel facilities",
    "parking": "Parking",
    "swimmingPool": "Swimming pool",
    "gym": "Gym",
    "breakfast": "Breakfast",
    "airConditioning": "Air conditioning",
    "noSmoking": "No smoking",
    "phone": "Phone",
    "safe": "Safe",
    "shower": "Shower",
    "wifi": "Wi-Fi",
    "spa": "Spa",
    "coffee": "Free coffee"
  },

  "hotelRules": {
    "title": "Hotel Rules",
    "noSmoking": "No smoking",
    "noAlcoholPool": "No alcohol or stimulants allowed in the pool",
    "childSupervision": "Children must always be supervised",
    "gymHours": "Gym: 5:00-7:00 AM and 5:00-8:00 PM",
    "restaurantHours": "Restaurant: Open from 6:00 AM to 10:00 PM"
  },

  "services": {
    "title": "Visit Our Famous Facilities",
    "ortherService": "Other Service",
    "dinning": {
      "title": "Restaurant & Dining Service",
      "subTitle": "A refined dining experience above the clouds of Tam Dao.",
      "details": " Located on the 11th floor, the GENUSS restaurant offers a harmonious blend of modern culinary touches and the rustic flavors of the mountain region. Guests can begin their morning with a generous buffet breakfast (7:00 AM - 9:00 AM), accompanied by complimentary tea, coffee, and bottled water in-room.\nLunch and dinner are served upon request, highlighting the freshest seasonal ingredients from Tam Dao: stir-fried su su shoots, mountain chicken, hill pork, sturgeon and salmon, stream bream, crispy chach fish, and local specialties such as Chuoi Ngu bananas, Sam Sua, wild pears, herbal leaves, bamboo rice, and hill porcupine.\nEvery dish is prepared with careful selection and a light, elegant cooking approach that preserves the purity of each ingredient.\nThe restaurant also caters to private dinners, celebrations, weddings, and conferences, with flexible banquet space designed to suit both intimate gatherings and high-class events.",
      "descriptions": "Indulge in a rich culinary journey with a delectable buffet breakfast and an enticing selection of Asian and European dishes. The warm and inviting ambiance, complemented by professional service, ensures every meal is both memorable and fulfilling."
    },
    "event": {
      "title": "Conference & Event Service",
      "subTitle": "A modern event space framed by the misty mountains of Tam Dao.",
      "details": " At Genuss Hotel Tam Dao - Hideaway Retreats, we offer a refined event venue of over 150 m², adaptable for everything from corporate conferences to elegant weddings. Every detail-from the sophisticated lighting and sound system to the custom-designed menus and banquet setup-is tailored to your occasion. Nestled amidst the mountain panorama and soft cloud mist of Tam Dao, the environment blends professional execution with relaxed luxury—ideal for both business and memorable gatherings.",
      "descriptions": "Offering an elegant setting ideal for meetings, weddings, and professional events, our venue is fully equipped with modern facilities and attentive service. We provide flexible solutions tailored to meet all your event needs with sophistication and precision."
    },
    "recreation": {
      "title": "Recreation & Wellness Service",
      "subTitle": "A serene space to rejuvenate your body and mind.",
      "details": "Located on the 2nd floor, the Fitness & Gym area at GENUSS is designed as a calm, modern wellness corner—perfect for energizing your morning or unwinding after a day exploring Tam Dao. The space features contemporary equipment, soft lighting and an airy layout that encourages focus and comfort throughout your workout.\nOperating during two daily sessions, 5:00-7:00 AM and 6:00-8:00 PM, the gym promotes a mindful and balanced training routine. Guests are encouraged to warm up thoroughly for 10–15 minutes, stay hydrated, and fuel their body properly before exercising. During the workout, maintaining correct form, respecting shared space, and listening to your body ensures both safety and efficiency. After finishing, gentle stretching and tidying up equipment help complete the session with ease.\nGENUSS' Recreation & Wellness area embraces the spirit of wellbeing—a quiet, refreshing pause within the mountain mist. It is a place to reconnect with yourself, restore your energy and nurture a sense of calm throughout your stay.",
      "descriptions": "Experience absolute relaxation at our year-round outdoor pool, modern fitness center, and premium leisure facilities. The serene and private environment offers the perfect retreat for families, couples, and travelers seeking an elevated and tranquil getaway."
    },
    "swimming": {
      "title": "All-Year Outdoor Swimming Pool",
      "subTitle": "A tranquil escape above the clouds of Tam Dao.",
      "details": "Located on the 12th floor, the outdoor pool at GENUSS offers a serene retreat above the clouds, where guests can immerse themselves in Tam Dao’s signature mist and expansive mountain views. Operating during 7:00–9:00 AM and 4:00–6:00 PM, the pool is maintained for optimal comfort and water quality. For safety, guests are asked to follow all pool guidelines: supervise children at all depths, refrain from bringing pets into the area, avoid jumping or sliding when the water level is low or the pool is not in operation, and limit alcohol or stimulants before swimming. This is a tranquil space to unwind, breathe deeply and embrace the quiet beauty of Tam Dao.",
      "descriptions": "Unwind by the outdoor pool, where crystal-clear waters blend harmoniously with the signature misty atmosphere of Tam Dao. The open, refreshing space with mountain views creates an exquisite and peaceful retreat for every guest."
    }
  },

  "contact": {
    "phone": "Phone",
    "location": {
      "title": "Location",
      "address": "Zone 1, Tam Dao commune, Phu Tho province",
      "viewOnGoogleMap": "View on Google Map"
    }
  },

  "bookingDetails": {
    "totalPrice": "Total Price",
    "table": {
      "rooms": "Rooms",
      "priceNight": "Price Night",
      "quantity": "Quantity"
    }
  },

  "roomData": {
    "bedTypes": {
      "largeDouble": "1 large double bed",
      "double": "1 double bed",
      "single": "1 single bed"
    },
    "viewTypes": {
      "square": "Square view",
      "mountain": "Mountain view",
      "city": "City",
      "church": "Church"
    },
    "bathroomTypes": {
      "bathtubShower": "Bathtub & Shower",
      "bathtub": "Bathtub",
      "shower": "Shower"
    },
    "features": {
      "sofa": "Sofa",
      "balcony": "Balcony",
      "romanticDecor": "Romantic decor"
    },
    "combined": "{a} / {b}"
  },

  "footer": {
    "contactUs": {
      "title": "contact us",
      "Tel": "Tel"
    },
    "hotelAddress": {
      "title": "Hotel Address",
      "address": "Zone 1, Tam Dao commune, Phu Tho province",
      "viewAllOffices": "View all office addresses",
      "offices": {
        "title": "Office Address",
        "cities": {
          "hanoi": {
            "name": "Hanoi",
            "offices": {
              "office1": "Office 1 - No. 175 Ngo Gia Tu - Viet Hung - Hanoi - 0978 700 968",
              "office2": "Office 2 - Floor 9, No. 85 Tran Thai Tong, Cau Giay, Hanoi - 0978 600 968"
            }
          },
          "haiphong": {
            "name": "Hai Phong",
            "offices": {
              "office1": "Office 1 - No. 16&18/33 Do Nhuan - Hai An - Hai Phong - 0978 500 968",
              "office2": "Office 2 - No. 326&328 Truong Chinh - Kien An - Hai Phong - 0978 044 968",
              "office3": "Office 3 - No. 41 Bach Dang, P Hai Duong, Hai Duong City - 0978 156 968"
            }
          },
          "ninhbinh": {
            "name": "Ninh Binh",
            "offices": {
              "office1": "Office 1 - No. 2/38 Dinh Tien Hoang - Hoa Lu - Ninh Binh - 0978 609 968",
              "office2": "Office 2 - No. 6 Tran Phu, Phu Ly, Ha Nam - 0978 704 968",
              "office3": "Office 3 - HVKT Building, No. 553 Truong Chinh Street - P Nam Dinh, Ninh Binh Province - 0978 605 968"
            }
          },
          "quangninh": {
            "name": "Quang Ninh",
            "offices": {
              "office1": "Office 1 - No. 169 Le Thanh Tong, Hong Gai, Quang Ninh - 0978 940 968"
            }
          },
          "bacninh": {
            "name": "Bac Ninh",
            "offices": {
              "office1": "Office 1 - No. 293 Le Loi, P Bac Giang, Bac Giang Province - 0978 053 968"
            }
          },
          "hungyen": {
            "name": "Hung Yen",
            "offices": {
              "office1": "Office 1 - No. 148 Chu Manh Trinh - Hien Nam - Hung Yen - 0978 430 968",
              "office2": "Office 2 - No. 604&608 Le Thanh Tong - 0978 420 968 & Thuy Dien Hotel, No. 285 Tran Thai Tong - Tran Hung Dao - Hung Yen - 0978 752 968",
              "office3": "Office 3 - No. 285 Tran Thai Tong - Tran Hung Dao - Hung Yen - 0978 752 968"
            }
          },
          "hochiminh": {
            "name": "Ho Chi Minh City",
            "offices": {
              "office1": "Office 1 - No. 48 Cat Tuong Street, Lovera Park, Phong Phu 4 Residential Area, Binh Chanh, Ho Chi Minh City - 0978 552 968"
            }
          }
        }
      }
    }
  }
};
export default messages;