import type { Metadata } from 'next';
import { Noto_Sans, Playfair_Display_SC } from 'next/font/google';
import '../globals.css';
import 'ldrs/react/Grid.css';
import { getMessages, setRequestLocale } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

const noto_Sans = Noto_Sans({
  subsets: ['latin'],
  variable: '--font-noto_sans',
});

const playfair_Display_SC = Playfair_Display_SC({
  subsets: ['latin'],
  variable: '--font-playfair_display_sc',
  weight: '400',
});

const playfair_Display_SC = Playfair_Display_SC({
  subsets: ['latin'],
  variable: '--font-playfair_display_sc',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Genuss Hotel',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  setRequestLocale(locale as 'en' | 'vi');
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`${noto_Sans.variable} ${playfair_Display_SC.variable} antialiased`}
      >
        <NextIntlClientProvider
          locale={locale as 'en' | 'vi'}
          messages={messages}
        >
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
