import type { Metadata } from 'next';
import { Noto_Sans, Allison } from 'next/font/google';
import '../globals.css';
import 'ldrs/react/Grid.css';
import { getMessages, setRequestLocale } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

const noto_Sans = Noto_Sans({
  subsets: ['latin'],
  variable: '--font-noto_sans',
});

const allison = Allison({
  subsets: ['latin'],
  variable: '--font-allison',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Genuss Hotel',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  setRequestLocale(locale);
  const messages = await getMessages();
  return (
    <html lang='en'>
      <body className={`${noto_Sans.variable} ${allison.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
